using System;
using System.Collections.Generic;

#nullable disable

namespace DataBase.Data
{
    public partial class Usuario
    {
        public int UsId { get; set; }
        public int UsGrupoBase { get; set; }
        public string UsUsuario { get; set; }
        public string UsNome { get; set; }
        public string UsUltimoNome { get; set; }
        public string UsSenha { get; set; }
        public int? UsMaxSessoes { get; set; }
        public string UsAtivo { get; set; }
        public DateTime Alteracao { get; set; }
        public int Usuario1 { get; set; }
        public int? UsProfConsReg { get; set; }
        public string UsEMedico { get; set; }
        public int? UsTipoUsuario { get; set; }
        public string UsSame { get; set; }
        public string UsFaturista { get; set; }
        public string UsInternamento { get; set; }
        public string UsTipoCaixa { get; set; }
        public int? UsEmpresa { get; set; }
        public int? UsSetor { get; set; }
        public string UsEmail { get; set; }
        public byte[] UsTemplate1 { get; set; }
        public byte[] UsTemplate2 { get; set; }
        public byte[] UsTemplate3 { get; set; }
        public byte[] UsTemplate4 { get; set; }
        public byte[] UsTemplate5 { get; set; }
        public int? UsTecnico { get; set; }
        public string UsEmailSenha { get; set; }
        public DateTime? UsExpira { get; set; }
        public int UsAddPlantaoManual { get; set; }
        public string UsCripto { get; set; }
        public byte[] UsSenhaCript { get; set; }
        public string UsCredenciamento { get; set; }
        public int? UsProfissional { get; set; }
        public string UsPaginaInicial { get; set; }
        public string UsRealizaLibera { get; set; }
        public string UsCpf { get; set; }
        public string UsRg { get; set; }
        public int? UsPeratual { get; set; }
        public string UsCodigoReset { get; set; }
        public string UsOrgao { get; set; }
        public string UsOrgaoUf { get; set; }
        public DateTime? UsDocEmi { get; set; }
        public string UsEstadoCivil { get; set; }
        public string UsSexo { get; set; }
        public DateTime? UsNascimento { get; set; }
        public string UsCns { get; set; }
        public string UsCnes { get; set; }
        public string UsCor { get; set; }
        public string UsEtnia { get; set; }
        public string UsPais { get; set; }
        public string UsNatural { get; set; }
        public string UsUfNatural { get; set; }
        public string UsReligiao { get; set; }
        public string UsEscol { get; set; }
        public string UsPis { get; set; }
        public string UsInss { get; set; }
        public string UsNomeSocial { get; set; }
        public string UsFreEscola { get; set; }
        public string UsSitFam { get; set; }
        public int? UsQtdDom { get; set; }
        public string UsNacionalidade { get; set; }
        public string UsSexoSocial { get; set; }
        public string UsMunNasc { get; set; }
        public string UsNasUf { get; set; }
        public string UsNumPass { get; set; }
        public string UsPaisPass { get; set; }
        public DateTime? UsEmiPass { get; set; }
        public DateTime? UsValPass { get; set; }
        public string UsNascPass { get; set; }
        public DateTime? UsDtEntPais { get; set; }
        public string UsPortariaNat { get; set; }
        public DateTime? UsPortariaData { get; set; }
        public string UsLogradouro { get; set; }
        public string UsEndereco { get; set; }
        public string UsComplemento { get; set; }
        public string UsNum1 { get; set; }
        public string UsBairro { get; set; }
        public string UsCidade { get; set; }
        public string UsEstado { get; set; }
        public string UsCep { get; set; }
        public string UsEmail2 { get; set; }
        public int? UsTpTel1 { get; set; }
        public int? UsTpTel2 { get; set; }
        public int? UsTpTel3 { get; set; }
        public string UsDddResidencia { get; set; }
        public string UsDddTrabalho { get; set; }
        public string UsDddFax { get; set; }
        public string UsTelefoneResidencia { get; set; }
        public string UsTelefoneTrabalho { get; set; }
        public string UsFax { get; set; }
        public string UsRamalResidencia { get; set; }
        public string UsRamalTrabalho { get; set; }
        public string UsRamalFax { get; set; }
        public string UsCtpsSerie { get; set; }
        public DateTime? UsCtpsEmi { get; set; }
        public DateTime? UsCtpsAdm { get; set; }
        public string UsCtpsCargo { get; set; }
        public string UsCtpsFuncao { get; set; }
        public string UsCtpsNumfun { get; set; }
        public int? UsCtpsTurno { get; set; }
        public string UsCtpsProf { get; set; }
        public string UsCtpsProfDesc { get; set; }
        public string UsCtpsOcu { get; set; }
        public string UsCtpsOcuDesc { get; set; }
        public string UsCertiTp { get; set; }
        public string UsCertiCart { get; set; }
        public DateTime? UsCertiEmi { get; set; }
        public string UsCertiLiv { get; set; }
        public string UsCertiFol { get; set; }
        public string UsCertiTer { get; set; }
        public string UsCnhNumero { get; set; }
        public string UsCnhUf { get; set; }
        public DateTime? UsCnhEmissao { get; set; }
        public string UsTitNum { get; set; }
        public string UsTitZona { get; set; }
        public string UsTitSecao { get; set; }
        public string UsAceitaTermo { get; set; }
        public DateTime? UsAceitaTermoDt { get; set; }
        public string UsTrocarSenha { get; set; }
        public byte[] UsSenhaCriptAterior { get; set; }
    }
}
